agent_name = "pcc-groq-llama"
image = "makeitmore/pcc-groq-llama:0.2"
image_credentials = "dockerhub"
secret_set = "pcc-groq-llama-secrets"
enable_krisp = true

[scaling]
min_agents = 2
max_agents = 50
